<?php

namespace ContainerOokugGW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlugifyServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SlugifyService' shared autowired service.
     *
     * @return \App\Service\SlugifyService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\SlugifyService": argument "$slugify" of method "__construct()" references class "Cocur\\Slugify\\Slugify" but no such service exists.');
    }
}
