<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK829Jvx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK829Jvx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK829Jvx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK829Jvx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK829Jvx\App_KernelDevDebugContainer([
    'container.build_hash' => 'K829Jvx',
    'container.build_id' => 'a96eddd2',
    'container.build_time' => 1757666805,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK829Jvx');
