<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQf2xnfU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQf2xnfU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQf2xnfU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQf2xnfU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQf2xnfU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qf2xnfU',
    'container.build_id' => 'c4d64ffb',
    'container.build_time' => 1757923822,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQf2xnfU');
