<?php

namespace ContainerK829Jvx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerlistProductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._PebHY_.App\Controller\ProductController::listProducts()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._PebHY_.App\\Controller\\ProductController::listProducts()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'slugifyService' => ['privates', 'App\\Service\\SlugifyService', 'getSlugifyServiceService', true],
        ], [
            'slugifyService' => 'App\\Service\\SlugifyService',
        ]))->withContext('App\\Controller\\ProductController::listProducts()', $container);
    }
}
