<?php

namespace ContainerK829Jvx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlugifyServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SlugifyService' shared autowired service.
     *
     * @return \App\Service\SlugifyService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SlugifyService.php';

        return $container->privates['App\\Service\\SlugifyService'] = new \App\Service\SlugifyService();
    }
}
